# Generated by Django 5.2.4 on 2025-07-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverproject', '0002_order_ccavenue_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
