# Generated by Django 5.2.4 on 2025-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverproject', '0002_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
