# Generated by Django 5.2.4 on 2025-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverproject', '0003_remove_order_paid_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ccavenue_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ccavenue_order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ccavenue_payment_mode',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='GST Number'),
        ),
    ]
