# Generated by Django 5.2.4 on 2025-07-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverproject', '0003_order_phone_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='1234567890', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
