# Generated by Django 5.2.4 on 2025-08-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverproject', '0004_remove_order_ccavenue_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
