# Generated by Django 5.2.4 on 2025-08-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverproject', '0005_alter_order_phone_alter_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('1_month', 'per month'), ('3_months', 'per 3 months'), ('6_months', 'per 6 months'), ('1_year', 'per year')], default='1_year', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
