# Generated by Django 5.2.4 on 2025-08-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverproject', '0006_remove_plan_description_plan_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('1_month', '/month'), ('3_months', '/3 months'), ('6_months', '/6 months'), ('1_year', '/year')], default='1_year', max_length=20),
        ),
    ]
