# Generated by Django 5.2.4 on 2025-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverproject', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='broker_name',
            field=models.CharField(choices=[('5paisa', '5paisa'), ('5paisa_xts', '5paisa (XTS)'), ('aliceblue', 'Aliceblue'), ('angelone', 'AngelOne'), ('compositedge_xts', 'Compositedge (XTS)'), ('dhan', 'Dhan'), ('dhan_sandbox', 'Dhan (Sandbox)'), ('firstock', 'Firstock'), ('flattrade', 'Flattrade'), ('fyers', 'Fyers'), ('groww', 'Groww'), ('iifl_xts', 'IIFL (XTS)'), ('indiabulls', 'IndiaBulls'), ('indmoney', 'IndMoney'), ('kotak_securities', 'Kotak Securities'), ('paytm', 'Paytm'), ('pocketful', 'Pocketful'), ('shoonya', 'Shoonya'), ('upstox', 'Upstox'), ('wisdom_capital_xts', 'Wisdom Capital (XTS)'), ('zebu', 'Zebu'), ('zerodha', 'Zerodha')], default='zerodha', max_length=100),
        ),
    ]
